name: teka_tekit
description: teka_teki_teku UI KIT
version: 1.11.0
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  patrol: ^3.7.1
  very_good_analysis: ^5.1.0
