name: build_ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    needs: determine-changes
    if: needs.determine-changes.outputs.projects != '[]' # Skip if no projects are changed
    strategy:
      matrix:
        project: ${{ fromJson(needs.determine-changes.outputs.projects) }}
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: ${{ matrix.project }}
      format_line_length: '160'
      flutter_version: '3.19.6'
      min_coverage: 60