name: teka_teki_tiku

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    strategy:
      matrix:
        project:
          - apps/teka_teki_tiku
          - apps/kakiku_admin
          - packages/naive_cross_word
          - packages/teka_tecore
          - packages/teka_tekit
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: ${{ matrix.project }}
      format_line_length: '160'
      flutter_version: '3.19.6'
      min_coverage: 60
  
  test:
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    strategy:
      matrix:
        project:
          - apps/teka_teki_tiku
          - apps/kakiku_admin
          - packages/naive_cross_word
          - packages/teka_tecore
          - packages/teka_tekit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ${{ matrix.project }}/coverage/lcov.info
          min_coverage: 0
