name: teka_teki_tiku

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    strategy:
      matrix:
        project:
          - apps/teka_teki_tiku
          - apps/kakiku_admin
          - packages/naive_cross_word
          - packages/teka_tecore
          - packages/teka_tekit
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: ${{ matrix.project }}
