name: Pull Request Workflow

concurrency:
  group: pull_request-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  determine-changes:
    name: Determine Changed Projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-changes.outputs.projects }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed projects and dependencies
        id: set-changes
        run: |
          # Define a dependency map
          declare -A dependency_map
          dependency_map["packages/naive_cross_word"]="apps/teka_teki_tiku"
          dependency_map["packages/teka_tecore"]="apps/teka_teki_tiku apps/kakiku_admin"
          dependency_map["packages/teka_tekit"]="apps/kakiku_admin"

          # Identify changed projects
          changed_projects=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} \
            | grep -E '^(apps|packages)/' | cut -d'/' -f1-2 | sort | uniq)

          # Include dependent projects
          affected_projects=""
          for project in $changed_projects; do
            affected_projects+="$project "
            if [[ -v dependency_map[$project] ]]; then
              affected_projects+="${dependency_map[$project]} "
            fi
          done

          # Set output
          echo "::set-output name=projects::$(echo $affected_projects | tr ' ' '\n' | sort | uniq | jq -R -s -c 'split("\n")[:-1]')"

  build:
    needs: determine-changes
    strategy:
      matrix:
        project: ${{ fromJson(needs.determine-changes.outputs.projects) }}
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: ${{ matrix.project }}
      format_line_length: '160'
      flutter_version: '3.19.6'
      min_coverage: 61
